"""Tiny FastAPI + HTMX UI for benchmark result JSON files."""

from __future__ import annotations

import argparse
import html
import json
import math
import os
import urllib.parse
from pathlib import Path
from typing import Any

try:  # Optional dependency: install with `.[benchmark-ui]`.
    from fastapi import FastAPI
    from fastapi import Request
    from fastapi.responses import FileResponse, HTMLResponse, JSONResponse, RedirectResponse
    from fastapi.responses import Response
    from fastapi.staticfiles import StaticFiles
except ModuleNotFoundError:  # pragma: no cover - exercised when optional deps are absent.
    FastAPI = None  # type: ignore[assignment]
    Request = None  # type: ignore[assignment]
    FileResponse = None  # type: ignore[assignment]
    HTMLResponse = None  # type: ignore[assignment]
    JSONResponse = None  # type: ignore[assignment]
    RedirectResponse = None  # type: ignore[assignment]
    Response = None  # type: ignore[assignment]
    StaticFiles = None  # type: ignore[assignment]

from athar_view.server import MANIFEST_SCHEMA_VERSION, build_report_bytes, find_dist


REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_BENCHMARK = REPO_ROOT / ".athar-benchmark" / "competitor-benchmark.json"
TOOLS = ("athar", "ifcdiff_default", "ifcdiff_relationships", "ifcfast")


def create_app(benchmark_path: str | Path | None = None):
    """Create the benchmark dashboard app.

    ``benchmark_path`` defaults to ``ATHAR_BENCHMARK_JSON`` and then the dated
    corpus benchmark generated by ``scripts/explore/benchmark_competitors.py``.
    """
    if FastAPI is None:
        raise RuntimeError("Install UI dependencies with: python -m pip install '.[benchmark-ui]'")

    path = Path(benchmark_path or os.getenv("ATHAR_BENCHMARK_JSON") or DEFAULT_BENCHMARK)
    app = FastAPI(title="Athar benchmark viewer")
    dist = find_dist()
    if dist is not None and StaticFiles is not None:
        app.mount("/viewer-app", StaticFiles(directory=dist, html=True), name="viewer-app")

    @app.get("/", response_class=HTMLResponse)
    def index() -> str:
        data = _load(path)
        rows = _filtered_rows(data, kind="all", assessment="all", tool="all")
        return _page(data, path, _controls(data), _table(rows), _insights(data))

    @app.get("/fragment/pairs", response_class=HTMLResponse)
    def pairs_fragment(
        kind: str = "all",
        assessment: str = "all",
        tool: str = "all",
    ) -> str:
        data = _load(path)
        return _table(_filtered_rows(data, kind=kind, assessment=assessment, tool=tool))

    @app.get("/api/benchmark")
    def benchmark_json() -> JSONResponse:
        return JSONResponse(_load(path))

    @app.get("/pair/{pair_name}", response_class=HTMLResponse)
    def pair_detail(pair_name: str) -> str:
        data = _load(path)
        pair = _pair_by_name(data, pair_name)
        if pair is None:
            return _not_found_page(f"Unknown benchmark pair: {pair_name}")
        return _pair_page(data, path, pair, viewer_available=dist is not None)

    @app.get("/viewer/{pair_name}")
    def viewer(pair_name: str, request: Request):
        data = _load(path)
        pair = _pair_by_name(data, pair_name)
        if pair is None:
            return Response(f"Unknown benchmark pair: {pair_name}", status_code=404)
        if dist is None:
            return Response("No viewer build found. Run `make viewer-build` first.", status_code=404)
        src = str(request.url_for("viewer_manifest_base", pair_name=pair_name)).removesuffix("/manifest.json")
        return RedirectResponse(url=f"/viewer-app/?src={urllib.parse.quote(src, safe='')}")

    @app.get("/viewer-src/{pair_name}/manifest.json", name="viewer_manifest_base")
    def viewer_manifest(pair_name: str, request: Request) -> JSONResponse:
        data = _load(path)
        pair = _pair_by_name(data, pair_name)
        if pair is None:
            return JSONResponse({"error": f"Unknown benchmark pair: {pair_name}"}, status_code=404)
        base = str(request.url).removesuffix("/manifest.json")
        old_path = _pair_input_path(pair, "old")
        new_path = _pair_input_path(pair, "new")
        return JSONResponse(
            {
                "athar_viewer_manifest": 1,
                "schema_version": MANIFEST_SCHEMA_VERSION,
                "generator": "athar_bench/ui",
                "old": {"name": old_path.name if old_path else "old.ifc", "url": f"{base}/files/old.ifc"},
                "new": {"name": new_path.name if new_path else "new.ifc", "url": f"{base}/files/new.ifc"},
                "report": {"url": f"{base}/files/report.json"},
            }
        )

    @app.get("/viewer-src/{pair_name}/files/{which}")
    def viewer_file(pair_name: str, which: str):
        data = _load(path)
        pair = _pair_by_name(data, pair_name)
        if pair is None:
            return Response(f"Unknown benchmark pair: {pair_name}", status_code=404)
        old_path = _pair_input_path(pair, "old")
        new_path = _pair_input_path(pair, "new")
        if which == "old.ifc" and old_path and old_path.is_file():
            return FileResponse(old_path, media_type="application/x-step", filename=old_path.name)
        if which == "new.ifc" and new_path and new_path.is_file():
            return FileResponse(new_path, media_type="application/x-step", filename=new_path.name)
        if which == "report.json" and old_path and new_path and old_path.is_file() and new_path.is_file():
            return Response(build_report_bytes(old_path, new_path), media_type="application/json")
        return Response(f"No benchmark viewer file: {which}", status_code=404)

    @app.get("/tool-output/{pair_name}/{tool}")
    def tool_output(pair_name: str, tool: str):
        data = _load(path)
        pair = _pair_by_name(data, pair_name)
        if pair is None:
            return Response(f"Unknown benchmark pair: {pair_name}", status_code=404)
        run = pair.get("runs", {}).get(tool)
        if not isinstance(run, dict):
            return Response(f"No output for {tool} on {pair_name}", status_code=404)
        if tool == "athar":
            old_path = _pair_input_path(pair, "old")
            new_path = _pair_input_path(pair, "new")
            if old_path and new_path and old_path.is_file() and new_path.is_file():
                return Response(build_report_bytes(old_path, new_path), media_type="application/json")
        output_path = _safe_existing_output_path(run.get("output"), benchmark_root=path.parent)
        if output_path is not None:
            return FileResponse(output_path, media_type="application/json", filename=output_path.name)
        preview = _tool_preview_payload(run)
        if preview is not None:
            return JSONResponse(preview)
        return Response(f"No saved output for {tool} on {pair_name}", status_code=404)

    @app.get("/favicon.ico", include_in_schema=False)
    def favicon() -> Response:
        return Response(status_code=204)

    return app


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Serve a local Athar benchmark dashboard")
    parser.add_argument("--benchmark", default=os.getenv("ATHAR_BENCHMARK_JSON", str(DEFAULT_BENCHMARK)))
    parser.add_argument("--static-out", help="write a static HTML dashboard instead of serving")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    args = parser.parse_args(argv)
    if args.static_out:
        html_text = render_static(args.benchmark)
        output_path = Path(args.static_out)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(html_text, encoding="utf-8")
        print(f"wrote {output_path}")
        return 0
    try:
        import uvicorn
    except ModuleNotFoundError as exc:  # pragma: no cover - optional dependency path.
        raise SystemExit("Install UI dependencies with: python -m pip install '.[benchmark-ui]'") from exc
    uvicorn.run(create_app(args.benchmark), host=args.host, port=args.port)
    return 0


def render_static(benchmark_path: str | Path) -> str:
    path = Path(benchmark_path)
    data = _load(path)
    rows = _filtered_rows(data, kind="all", assessment="all", tool="all")
    return _page(data, path, "", _table(rows), _insights(data))


def _load(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def _filtered_rows(data: dict[str, Any], *, kind: str, assessment: str, tool: str) -> list[dict[str, Any]]:
    rows = list(data.get("summary", []))
    if kind != "all":
        rows = [row for row in rows if row.get("kind") == kind]
    if assessment != "all":
        rows = [row for row in rows if assessment in row.get("assessment", {}).values()]
    if tool != "all":
        rows = [row for row in rows if tool in row and (assessment == "all" or row.get("assessment", {}).get(tool) == assessment)]
    return rows


def _controls(data: dict[str, Any]) -> str:
    kinds = sorted({row.get("kind", "unknown") for row in data.get("summary", [])})
    tool_options = [tool for tool in TOOLS if any(tool in row for row in data.get("summary", []))]
    return f"""
    <form class="row g-3 align-items-end mb-4" hx-get="/fragment/pairs" hx-target="#pair-table" hx-trigger="change, keyup delay:200ms">
      <div class="col-12 col-md-4">
        <label class="form-label" for="kind">Pair kind</label>
        {_select("kind", ["all", *kinds])}
      </div>
      <div class="col-12 col-md-4">
        <label class="form-label" for="assessment">Assessment</label>
        {_select("assessment", ["all", "expected", "unexpected", "observed", "not_run"])}
      </div>
      <div class="col-12 col-md-4">
        <label class="form-label" for="tool">Tool</label>
        {_select("tool", ["all", *tool_options])}
      </div>
    </form>
    """


def _select(name: str, values: list[str]) -> str:
    options = "".join(f'<option value="{_e(value)}">{_label(value)}</option>' for value in values)
    return f'<select id="{_e(name)}" name="{_e(name)}" class="form-select">{options}</select>'


def _table(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return '<section id="pair-table" class="alert alert-secondary">No benchmark pairs match those filters.</section>'
    body = "".join(_row(row) for row in rows)
    return f"""
    <section id="pair-table" class="table-responsive" aria-live="polite">
      <table class="table table-sm table-striped table-hover align-top">
        <thead class="table-light">
          <tr>
            <th>Pair</th>
            <th>Expectation</th>
            <th>Athar</th>
            <th>IfcDiff</th>
            <th>IfcDiff + relationships</th>
            <th>IfcFast</th>
          </tr>
        </thead>
        <tbody>{body}</tbody>
      </table>
    </section>
    """


def _row(row: dict[str, Any]) -> str:
    name = row.get("name", "unknown")
    return f"""
    <tr>
      <td>
        <strong><a href="/pair/{_url(name)}">{_e(name)}</a></strong>
        <div><span class="badge text-bg-light border">{_e(row.get("kind", "unknown"))}</span></div>
        <div class="small"><a href="/viewer/{_url(name)}" target="_blank" rel="noreferrer">viewer</a> · <a href="/pair/{_url(name)}">outputs</a></div>
      </td>
      <td class="text-secondary">{_e(row.get("expectation", ""))}</td>
      {_tool_cell(row, "athar")}
      {_tool_cell(row, "ifcdiff_default")}
      {_tool_cell(row, "ifcdiff_relationships")}
      {_tool_cell(row, "ifcfast")}
    </tr>
    """


def _tool_cell(row: dict[str, Any], tool: str) -> str:
    result = row.get(tool)
    if not isinstance(result, dict):
        return '<td class="text-secondary">—</td>'
    assessment = row.get("assessment", {}).get(tool, "observed")
    counts = result.get("counts") or {}
    time_s = result.get("seconds_median")
    rss = result.get("peak_rss_mb_max")
    gb_s = result.get("gb_seconds_median")
    title = _assessment_title(assessment)
    output = f'<div class="small"><a href="/tool-output/{_url(row.get("name", "unknown"))}/{_url(tool)}">output</a></div>'
    return f"""
    <td class="tool-cell">
      <span class="badge {_badge_class(assessment)}" title="{_e(title)}">{_label(assessment)}</span>
      <div class="font-monospace small mt-1">+{counts.get("added", "?")} −{counts.get("deleted", "?")} ~{counts.get("modified", "?")} ={counts.get("unchanged", "—")}</div>
      <div class="text-secondary small">{_metric(time_s, "s")} · {_metric(rss, "MB")} · {_metric(gb_s, "GB·s")}</div>
      {output}
    </td>
    """


def _insights(data: dict[str, Any]) -> str:
    rows = data.get("summary", [])
    return _tool_averages(rows)


def _tool_averages(rows: list[dict[str, Any]]) -> str:
    stats = [_tool_average_stats(rows, tool) for tool in TOOLS]
    ranges = {
        "correctness": [stat["correctness_value"] for stat in stats if stat["correctness_value"] is not None],
        "unexpected": [stat["unexpected"] for stat in stats],
        "avg_time": [stat["avg_time_value"] for stat in stats if stat["avg_time_value"] is not None],
        "avg_rss": [stat["avg_rss_value"] for stat in stats if stat["avg_rss_value"] is not None],
        "avg_gbs": [stat["avg_gbs_value"] for stat in stats if stat["avg_gbs_value"] is not None],
    }
    body = "".join(_tool_average_row(stat, ranges) for stat in stats)
    return f"""
    <section class="mb-4" aria-label="Tool averages">
      <h2 class="h5">Tool averages</h2>
      <div class="table-responsive">
        <table class="table table-sm align-middle mb-0">
          <thead class="table-light">
            <tr>
              <th>Tool</th>
              <th>Correctness</th>
              <th>Judged pairs</th>
              <th>Unexpected</th>
              <th>Avg median time</th>
              <th>Avg peak RSS</th>
              <th>Avg GB·s</th>
            </tr>
          </thead>
          <tbody>{body}</tbody>
        </table>
      </div>
    </section>
    """


def _tool_average_stats(rows: list[dict[str, Any]], tool: str) -> dict[str, Any]:
    judged = 0
    expected = 0
    unexpected = 0
    times: list[float] = []
    rss_values: list[float] = []
    gbs_values: list[float] = []
    for row in rows:
        result = row.get(tool)
        if not isinstance(result, dict):
            continue
        assessment = row.get("assessment", {}).get(tool)
        if assessment in {"expected", "unexpected"}:
            judged += 1
            expected += assessment == "expected"
            unexpected += assessment == "unexpected"
        time_s = result.get("seconds_median")
        if isinstance(time_s, (int, float)) and not (isinstance(time_s, float) and math.isnan(time_s)):
            times.append(float(time_s))
        rss = result.get("peak_rss_mb_max")
        if isinstance(rss, (int, float)) and not (isinstance(rss, float) and math.isnan(rss)):
            rss_values.append(float(rss))
        gb_s = result.get("gb_seconds_median")
        if isinstance(gb_s, (int, float)) and not (isinstance(gb_s, float) and math.isnan(gb_s)):
            gbs_values.append(float(gb_s))

    correctness_value = None if judged == 0 else expected / judged
    avg_time_value = None if not times else sum(times) / len(times)
    avg_rss_value = None if not rss_values else sum(rss_values) / len(rss_values)
    avg_gbs_value = None if not gbs_values else sum(gbs_values) / len(gbs_values)
    return {
        "tool": tool,
        "judged": judged,
        "unexpected": unexpected,
        "correctness_value": correctness_value,
        "correctness": "—" if correctness_value is None else f"{correctness_value:.0%}",
        "avg_time_value": avg_time_value,
        "avg_time": "—" if avg_time_value is None else f"{avg_time_value:.3g} s",
        "avg_gbs_value": avg_gbs_value,
        "avg_gbs": "—" if avg_gbs_value is None else f"{avg_gbs_value:.3g} GB·s",
        "avg_rss_value": avg_rss_value,
        "avg_rss": "—" if avg_rss_value is None else f"{avg_rss_value:.3g} MB",
    }


def _tool_average_row(stat: dict[str, Any], ranges: dict[str, list[float | int]]) -> str:
    return f"""
    <tr>
      <td>{_label(stat["tool"])}</td>
      <td class="{_range_class(stat["correctness_value"], ranges["correctness"], higher_is_better=True)}">{_e(stat["correctness"])}</td>
      <td>{stat["judged"]}</td>
      <td class="{_range_class(stat["unexpected"], ranges["unexpected"], higher_is_better=False)}">{stat["unexpected"]}</td>
      <td class="font-monospace {_range_class(stat["avg_time_value"], ranges["avg_time"], higher_is_better=False)}">{_e(stat["avg_time"])}</td>
      <td class="font-monospace {_range_class(stat["avg_rss_value"], ranges["avg_rss"], higher_is_better=False)}">{_e(stat["avg_rss"])}</td>
      <td class="font-monospace {_range_class(stat["avg_gbs_value"], ranges["avg_gbs"], higher_is_better=False)}">{_e(stat["avg_gbs"])}</td>
    </tr>
    """


def _range_class(value: float | int | None, values: list[float | int], *, higher_is_better: bool) -> str:
    if value is None or len(set(values)) < 2:
        return ""
    best = max(values) if higher_is_better else min(values)
    worst = min(values) if higher_is_better else max(values)
    if value == best:
        return "table-success"
    if value == worst:
        return "table-danger"
    return "table-warning"


def _page(data: dict[str, Any], path: Path, controls: str, table: str, insights: str) -> str:
    generated = data.get("generated_at", "unknown")
    settings = data.get("settings", {})
    tools = data.get("tools", {})
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Athar benchmark viewer</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://unpkg.com/htmx.org@2.0.4" defer></script>
  <style>{_css()}</style>
</head>
<body>
  <main class="container-fluid py-4">
    <header class="mb-4">
      <h1 class="h2">Benchmark results</h1>
      <p class="text-secondary mb-2">Semantic IFC diff benchmark output.</p>
      <dl class="row small mb-0">
        <dt class="col-sm-2 col-lg-1">Generated</dt><dd class="col-sm-10 col-lg-11 font-monospace">{_e(generated)}</dd>
        <dt class="col-sm-2 col-lg-1">Repeats</dt><dd class="col-sm-10 col-lg-11 font-monospace">{_e(settings.get("repeats", "—"))}</dd>
      </dl>
    </header>
    {insights}
    <section class="mb-4">{_tool_strip(tools)}</section>
    {controls}
    {table}
  </main>
</body>
</html>"""


def _pair_page(data: dict[str, Any], path: Path, pair: dict[str, Any], *, viewer_available: bool) -> str:
    name = pair.get("name", "unknown")
    old_path = _pair_input_path(pair, "old")
    new_path = _pair_input_path(pair, "new")
    viewer = (
        f'<a class="btn btn-primary" href="/viewer/{_url(name)}" target="_blank" rel="noreferrer">Open Athar viewer</a>'
        if viewer_available and old_path and new_path and old_path.is_file() and new_path.is_file()
        else '<span class="text-secondary">Viewer unavailable: run <code>make viewer-build</code> and ensure input IFCs exist locally.</span>'
    )
    outputs = "".join(_tool_output_card(name, tool, run) for tool, run in pair.get("runs", {}).items() if isinstance(run, dict))
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{_e(name)} · Athar benchmark viewer</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>{_css()}</style>
</head>
<body>
  <main class="container-fluid py-4">
    <p><a href="/">← Benchmark results</a></p>
    <header class="mb-4">
      <h1 class="h3">{_e(name)}</h1>
      <p class="text-secondary mb-2">{_e(pair.get("expectation", ""))}</p>
      <div class="mb-3">{viewer}</div>
      <dl class="row small mb-0">
        <dt class="col-sm-2 col-lg-1">Kind</dt><dd class="col-sm-10 col-lg-11">{_e(pair.get("kind", "unknown"))}</dd>
        <dt class="col-sm-2 col-lg-1">Old</dt><dd class="col-sm-10 col-lg-11 font-monospace">{_e(old_path or "—")}</dd>
        <dt class="col-sm-2 col-lg-1">New</dt><dd class="col-sm-10 col-lg-11 font-monospace">{_e(new_path or "—")}</dd>
      </dl>
    </header>
    <section class="mb-4">
      <h2 class="h5">Tool outputs</h2>
      <div class="row g-3">{outputs}</div>
    </section>
    <section>
      <h2 class="h5">Full benchmark pair JSON</h2>
      <pre class="json-block">{_e(json.dumps(pair, indent=2, sort_keys=True))}</pre>
    </section>
  </main>
</body>
</html>"""


def _tool_output_card(pair_name: str, tool: str, run: dict[str, Any]) -> str:
    counts = _run_counts(run) or {}
    body = _tool_preview_text(run)
    return f"""
    <div class="col-12 col-xl-6">
      <article class="card h-100">
        <div class="card-body">
          <h3 class="h6 card-title">{_label(tool)}</h3>
          <div class="font-monospace small mb-2">+{counts.get("added", "?")} −{counts.get("deleted", "?")} ~{counts.get("modified", "?")} ={counts.get("unchanged", "—")}</div>
          <p class="small mb-2"><a href="/tool-output/{_url(pair_name)}/{_url(tool)}">Open raw output</a></p>
          <pre class="preview-block">{_e(body)}</pre>
        </div>
      </article>
    </div>
    """


def _not_found_page(message: str) -> str:
    return f"""<!doctype html><html lang="en"><body><main><p><a href="/">← Benchmark results</a></p><h1>Not found</h1><p>{_e(message)}</p></main></body></html>"""


def _tool_strip(tools: dict[str, Any]) -> str:
    cards = []
    for name, info in tools.items():
        version = info.get("version") or ("available" if info.get("available") else "not installed")
        cards.append(f'<span class="badge text-bg-light border me-2 mb-2">{_label(name)}: <span class="font-monospace">{_e(version)}</span></span>')
    return "".join(cards)


def _metric(value: Any, suffix: str) -> str:
    if not isinstance(value, (int, float)) or (isinstance(value, float) and math.isnan(value)):
        return f"— {suffix}"
    return f"{value:g} {suffix}"


def _label(value: Any) -> str:
    if value == "observed":
        return "Not Judged"
    if value == "not_run":
        return "Not Run"
    return str(value).replace("_", " ").title()


def _badge_class(assessment: str) -> str:
    return {
        "expected": "text-bg-success",
        "unexpected": "text-bg-danger",
        "observed": "text-bg-secondary",
        "not_run": "text-bg-secondary",
    }.get(assessment, "text-bg-secondary")


def _assessment_title(assessment: str) -> str:
    return {
        "expected": "Matches the encoded expected outcome for this benchmark pair.",
        "unexpected": "Does not match the encoded expected outcome for this benchmark pair.",
        "observed": "No pass/fail expectation is encoded for this pair/tool; result is shown for reference only and excluded from correctness.",
        "not_run": "This tool was not run for this benchmark pair.",
    }.get(assessment, "Benchmark assessment")


def _e(value: Any) -> str:
    return html.escape(str(value), quote=True)


def _url(value: Any) -> str:
    return urllib.parse.quote(str(value), safe="")


def _pair_by_name(data: dict[str, Any], pair_name: str) -> dict[str, Any] | None:
    return next((pair for pair in data.get("pairs", []) if pair.get("name") == pair_name), None)


def _pair_input_path(pair: dict[str, Any], side: str) -> Path | None:
    value = pair.get(side, {}).get("path") if isinstance(pair.get(side), dict) else None
    if not isinstance(value, str) or not value:
        return None
    return Path(value)


def _safe_existing_output_path(value: Any, *, benchmark_root: Path) -> Path | None:
    if not isinstance(value, str) or not value:
        return None
    path = Path(value)
    if not path.is_absolute():
        path = REPO_ROOT / path
    try:
        resolved = path.resolve()
        allowed_roots = [benchmark_root.resolve(), (REPO_ROOT / ".athar-benchmark").resolve()]
        if not any(resolved == root or resolved.is_relative_to(root) for root in allowed_roots):
            return None
    except OSError:
        return None
    return resolved if resolved.is_file() else None


def _tool_preview_payload(run: dict[str, Any]) -> Any:
    if "output_preview" in run:
        return run["output_preview"]
    previews = {key: run.get(key) for key in ("stdout_preview", "stderr_preview") if run.get(key)}
    return previews or None


def _tool_preview_text(run: dict[str, Any]) -> str:
    preview = _tool_preview_payload(run)
    if preview is None:
        return "No inline preview saved."
    if isinstance(preview, str):
        return preview
    return json.dumps(preview, indent=2, sort_keys=True)


def _run_counts(run: dict[str, Any]) -> dict[str, Any] | None:
    counts = run.get("counts") or run.get("sections")
    return counts if isinstance(counts, dict) else None


def _css() -> str:
    return """
    .table { min-width: 1120px; }
    .tool-cell { min-width: 160px; }
    td:first-child { min-width: 260px; }
    td:nth-child(2) { min-width: 260px; max-width: 360px; }
    .json-block, .preview-block {
      background: #0f172a;
      border-radius: .5rem;
      color: #e2e8f0;
      max-height: 32rem;
      overflow: auto;
      padding: 1rem;
      white-space: pre-wrap;
    }
    .preview-block { max-height: 18rem; }
    """


if __name__ == "__main__":
    raise SystemExit(main())
